# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
notifications:
  email: false
  webhooks:
    urls:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false